addSbtPlugin("org.scala-js"                % "sbt-scalajs"              % "1.15.0")
addSbtPlugin("io.spray"                    % "sbt-revolver"             % "0.10.0")
addSbtPlugin("ch.epfl.scala"               % "sbt-bloop"                % "1.5.11")
addSbtPlugin("org.portable-scala"          % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("com.eed3si9n"                % "sbt-assembly"             % "2.1.3")
addSbtPlugin("com.eed3si9n"                % "sbt-buildinfo"            % "0.11.0")
