addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.12.0")
addSbtPlugin("io.spray"           % "sbt-revolver"             % "0.9.1")
addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"                % "1.5.4")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"             % "0.15.0")
