name: Deploy to fly.io

on:
  push:
    branches: [publish]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up NPM 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install npm deps
        run: cd frontend && npm ci && cd ..
      - name: Compile
        run: sbt compile
      - name: Run tests
        run: sbt test
      - name: Build application
        run: sbt packageApplication
      - name: Deploy to fly.io
        run: flyctl deploy --remote-only
